apiVersion: v1
data:
  agent.yaml: "data_dir: /vector-data-dir\napi:\n  enabled: true\n  address: 127.0.0.1:8686\n  playground: false\nsources:\n
    \ kubernetes_logs:\n    type: kubernetes_logs\n  host_metrics:\n    filesystem:\n      devices:\n        excludes: [binfmt_misc]\n
    \     filesystems:\n        excludes: [binfmt_misc]\n      mountpoints:\n        excludes: [\"*/proc/sys/fs/binfmt_misc\"]\n
    \   type: host_metrics\n  internal_metrics:\n    type: internal_metrics\nsinks:\n  prom_exporter:\n    type: prometheus_exporter\n
    \   inputs: [host_metrics, internal_metrics]\n    address: 0.0.0.0:9090\n  stdout:\n    type: console\n    inputs: [kubernetes_logs]\n
    \   encoding:\n      codec: json\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: Agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.51.1-distroless-libc
    helm.sh/chart: vector-0.48.0
  name: vector
  namespace: core-vector
