# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/Application--core-argocd--cluster-namespaces.yaml
  - resources/ApplicationSet--core-argocd--core-app-multi.yaml
  - resources/ApplicationSet--core-argocd--core-app-single.yaml
  - resources/ApplicationSet--core-argocd--core-crds.yaml
  - resources/ApplicationSet--core-argocd--core-usage.yaml
  - resources/ApplicationSet--core-argocd--home-media.yaml
