apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: reloader
    meta.helm.sh/release-namespace: core-reloader
  labels:
    app: reloader-reloader
    app.kubernetes.io/instance: reloader
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: reloader
    app.kubernetes.io/version: v1.4.10
    chart: reloader-2.2.5
    helm.sh/chart: reloader-2.2.5
    heritage: Helm
    release: reloader
  name: reloader-reloader-metadata-role-binding
  namespace: core-reloader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reloader-reloader-metadata-role
subjects:
  - kind: ServiceAccount
    name: reloader-reloader
    namespace: core-reloader
