apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: reloader
    meta.helm.sh/release-namespace: core-reloader
  labels:
    app: reloader-reloader
    app.kubernetes.io/instance: reloader
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: reloader
    app.kubernetes.io/version: v1.4.9
    chart: reloader-2.2.4
    helm.sh/chart: reloader-2.2.4
    heritage: Helm
    release: reloader
  name: reloader-reloader
  namespace: core-reloader
