[tools]
"aqua:nushell/nushell" = "latest"
"go:github.com/artuross/kubesource/cmd/kubesource" = "latest"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"

crane = "latest"
fd = "latest"
go = "latest"
just = "latest"
talhelper = "latest"
talosctl = "1.12.4"

[settings]
experimental = true
lockfile = true
