apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/version: v1.1.0
    helm.sh/chart: external-secrets-1.1.0
  name: external-secrets-cert-controller
  namespace: core-external-secrets
