apiVersion: v1
data:
  redis_liveness.sh: "response=$(\n  redis-cli \\\n    -a \"${REDIS_PASSWORD}\" --no-auth-warning \\\n    -h localhost \\\n
    \   -p 6379 \\\n    ping\n)\nif [ \"$response\" != \"PONG\" ] && [ \"${response:0:7}\" != \"LOADING\" ] ; then\n  echo
    \"$response\"\n  exit 1\nfi\necho \"response=$response\"\n"
  redis_readiness.sh: "response=$(\n  redis-cli \\\n    -a \"${REDIS_PASSWORD}\" --no-auth-warning \\\n    -h localhost \\\n
    \   -p 6379 \\\n    ping\n)\nif [ \"$response\" != \"PONG\" ] ; then\n  echo \"$response\"\n  exit 1\nfi\necho \"response=$response\"\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.2.2
    helm.sh/chart: argo-cd-9.1.10
  name: argocd-redis-health-configmap
  namespace: core-argocd
