# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: argo-cd
    namespace: core-argocd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    includeCRDs: true
    version: 9.3.7
    valuesFile: values.yaml
