apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: exit-node-home
  namespace: core-tailscale
spec:
  replicas: 1
  hostnamePrefix: exit-node-home
  exitNode: true
  subnetRouter:
    advertiseRoutes:
      - "192.168.0.0/24"
