apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: kite
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kite
    app.kubernetes.io/version: v0.7.6
    helm.sh/chart: kite-0.7.6
  name: kite
  namespace: core-kite
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kite
      app.kubernetes.io/name: kite
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kite
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kite
        app.kubernetes.io/version: v0.7.6
        helm.sh/chart: kite-0.7.6
    spec:
      containers:
        - command:
            - /app/kite
          env: null
          envFrom:
            - secretRef:
                name: kite-secret
          image: ghcr.io/zxh326/kite:v0.7.6
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          name: kite
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts: null
      serviceAccountName: kite
      volumes: null
