apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: kite
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kite
    app.kubernetes.io/version: v0.7.5
    helm.sh/chart: kite-0.7.5
  name: kite
  namespace: core-kite
