apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: kite
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kite
    app.kubernetes.io/version: v0.7.5
    helm.sh/chart: kite-0.7.5
  name: kite
  namespace: core-kite
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: kite
    app.kubernetes.io/name: kite
  type: ClusterIP
