# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cloudnative-pg
    namespace: core-cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    releaseName: cnpg
    includeCRDs: true
    version: 0.27.0
    valuesFile: values.yaml
