apiVersion: kubesource.rcwz.pl/v1alpha2
kind: Config
sources:
  - sourceDir: _source
    targets:
      - directory: app/base
        filter:
          exclude:
            - kind: CustomResourceDefinition
      - directory: crds
        filter:
          include:
            - kind: CustomResourceDefinition
