apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qui
  namespace: home-media
spec:
  secretName: certificate-qui

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always

  duration: 720h # 30d
  renewBefore: 240h # 10d

  dnsNames:
    - qui.rcwz.pl

  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt
