apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: qui
  namespace: home-media
spec:
  endpoints:
    - dnsName: qui.rcwz.pl
      recordTTL: 60
      recordType: CNAME
      targets:
        - ingress.k8s.rcwz.pl
