apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-oidc
  namespace: home-media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: qui-oidc
    creationPolicy: Owner
  data:
    - secretKey: clientId
      remoteRef:
        key: pocketid.oidc.qui
        property: client_id

    - secretKey: clientSecret
      remoteRef:
        key: pocketid.oidc.qui
        property: client_secret
