apiVersion: v1
kind: Service
metadata:
  name: qui
  namespace: home-media
spec:
  type: ClusterIP
  selector:
    app: qui
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 7476
