# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: connect
    namespace: core-1password-connect
    repo: https://1password.github.io/connect-helm-charts/
    releaseName: connect
    includeCRDs: false
    version: 2.2.0
    valuesFile: values.yaml
