# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: vector
    namespace: core-vector
    repo: https://helm.vector.dev
    releaseName: vector
    includeCRDs: true
    version: 0.49.0
    valuesFile: values.yaml
