# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: external-dns
    namespace: core-external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    releaseName: external-dns
    includeCRDs: true
    version: 1.20.0
    valuesFile: values.yaml
