apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: credentials-artuross-homelab-internal
  namespace: core-argocd
spec:
  secretStoreRef:
    name: 1password
    kind: ClusterSecretStore
  target:
    name: credentials-artuross-homelab-internal
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:artuross/homelab-internal
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: services.github.ssh
        property: private key
