apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.8.1
    helm.sh/chart: connect-2.3.0
  name: onepassword-connect
  namespace: core-1password-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
        app.kubernetes.io/component: connect
        version: 1.8.1
    spec:
      containers:
        - env:
            - name: OP_SESSION
              value: /home/opuser/.op/1password-credentials.json
            - name: OP_BUS_PORT
              value: "11220"
            - name: OP_BUS_PEERS
              value: localhost:11221
            - name: OP_HTTP_PORT
              value: "8080"
            - name: OP_LOG_LEVEL
              value: info
          image: 1password/connect-api:1.8.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /heartbeat
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
          name: connect-api
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 0.2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
            - mountPath: /home/opuser/.op/1password-credentials.json
              name: credentials
              subPath: 1password-credentials.json
        - env:
            - name: OP_HTTP_PORT
              value: "8081"
            - name: OP_SESSION
              value: /home/opuser/.op/1password-credentials.json
            - name: OP_BUS_PORT
              value: "11221"
            - name: OP_BUS_PEERS
              value: localhost:11220
            - name: OP_LOG_LEVEL
              value: info
          image: 1password/connect-sync:1.8.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /heartbeat
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
          name: connect-sync
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
            - mountPath: /home/opuser/.op/1password-credentials.json
              name: credentials
              subPath: 1password-credentials.json
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
      tolerations: []
      volumes:
        - emptyDir: {}
          name: shared-data
        - name: credentials
          secret:
            items:
              - key: 1password-credentials.json
                path: 1password-credentials.json
            secretName: op-credentials
