apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.8.1
    helm.sh/chart: connect-2.3.0
  name: onepassword-connect
  namespace: core-1password-connect
spec:
  ports:
    - name: connect-sync
      port: 8081
    - name: connect-api
      port: 8080
  selector:
    app: onepassword-connect
  type: ClusterIP
