# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: tailscale-operator
    namespace: core-tailscale
    repo: https://pkgs.tailscale.com/helmcharts
    releaseName: tailscale-operator
    includeCRDs: true
    version: 1.90.8
    valuesFile: values.yaml
