# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cert-manager
    namespace: core-cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    includeCRDs: true
    skipHooks: true
    version: v1.19.3
    valuesFile: values.yaml
